export const supportedCurrencies = {
  // GBP: { name: "British Pound Sterling", countryCode: "GB" },
  CAD: { name: "Canadian Dollar", countryCode: "CA" },
  NGN: { name: "Nigerian Naira", countryCode: "NG" },
  USD: { name: "United States Dollar", countryCode: "US" },
  // ZAR: { name: "South African Rand", countryCode: "ZA" },
  // XAF: { name: "Central African CFA Franc", countryCode: "CF" },
  // CLP: { name: "Chilean Peso", countryCode: "CL" },
  // COP: { name: "Colombian Peso", countryCode: "CO" },
  // EGP: { name: "Egyptian Pound", countryCode: "EG" },
  // EUR: { name: "SEPA", countryCode: "EU" },
  // GHS: { name: "Ghanaian Cedi", countryCode: "GH" },
  // GNF: { name: "Guinean Franc", countryCode: "GN" },
  // KES: { name: "Kenyan Shilling", countryCode: "KE" },
  // MWK: { name: "Malawian Kwacha", countryCode: "MW" },
  // MAD: { name: "Moroccan Dirham", countryCode: "MA" },
  // RWF: { name: "Rwandan Franc", countryCode: "RW" },
  // SLL: { name: "Sierra Leonean Leone", countryCode: "SL" },
  // TZS: { name: "Tanzanian Shilling", countryCode: "TZ" },
  // UGX: { name: "Ugandan Shilling", countryCode: "UG" },
  // XOF: { name: "West African CFA Franc BCEAO", countryCode: "WA" },
  // ZMW: { name: "Zambian Kwacha", countryCode: "ZM" },
};
